name: Deploy Example Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Step 3: Copy the theme into the exampleSite/themes directory
      - name: Copy theme to exampleSite
        run: |
          mkdir -p exampleSite/themes/AltitudeDark
          rsync -av --exclude=exampleSite --exclude=.git ./ exampleSite/themes/AltitudeDark

      # Step 4: Update baseURL in hugo.toml
      - name: Update baseURL
        run: |
          sed -i 's|https://example.org/|https://1090mhz.github.io/|' exampleSite/hugo.toml

      # Step 5: Build the exampleSite
      - name: Build exampleSite
        run: |
          cd exampleSite
          hugo --minify

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: exampleSite/public  # Hugo's default output directory
          publish_branch: gh-pages