name: Deploy Example Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Copy exampleSite contents
        run: |
          cp -r exampleSite/* .  # Copy all contents from exampleSite into the root folder
      # Step 3: Build the exampleSite
      - name: Build exampleSite
        run: |
          cd exampleSite
          hugo --minify

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Hugo's default output directory
          publish_branch: gh-pages
